---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: truck-APP_NAME
  #namespace: logistic
  labels:
    app: truck-APP_NAME
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: truck-APP_NAME
  template:
    metadata:
      labels:
        app: truck-APP_NAME
        date: "_DATE_"
    spec:
      #imagePullSecrets:
      #- name: regcred
      terminationGracePeriodSeconds: 180
      restartPolicy: Always
      containers:
      - name: truck-APP_NAME
        image: asia.gcr.io/ghn-logistic/logistic_thangtest:_VERSION_
        ports:
        - containerPort: 9090
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: env-env
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "750Mi"
            cpu: "750m"
---
