kind: Service
apiVersion: v1
metadata:
  name: truck-APP_NAME
  #namespace: station
spec:
  selector:
    app: truck-APP_NAME
  type: NodePort # Test kong ingress
  ports:
  ####### Kong Ingress
  - port: 8080
    targetPort: 9090
    protocol: TCP
    name: truck-APP_NAME
---
# Kong Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: truck-APP_NAME
  #namespace:  dummy
  annotations:
    kubernetes.io/ingress.class: "kong"
    configuration.konghq.com: kong-ingress
spec:
  rules:
    - host: staging-truck-gw.ghn.vn
      http:
        paths:
          - path: "/api/v2/public/customer"
            backend:
              serviceName: truck-APP_NAME
              servicePort: truck-APP_NAME
          - path: "/api/v2/staff/customer"
            backend:
              serviceName: truck-APP_NAME
              servicePort: truck-APP_NAME
          - path: "/api/v2/private/customer"
            backend:
              serviceName: truck-APP_NAME
              servicePort: truck-APP_NAME
          - path: "/api/v2/internal/customer"
            backend:
              serviceName: truck-APP_NAME
              servicePort: truck-APP_NAME
